name: Checkout
on: [push]
jobs:
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List files before
              run: ls -a

            - name: Checkout
              run: |
                  git init
                  git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                  git fetch origin
                  git branch
                  git checkout main
            - name: List files after
              run: ls -a
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: List files before
              run: ls -a
            - name: Checkout with actions from market place
              uses: actions/checkout@v3
            - name: List files after
              run: ls -a
