name: First Workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Echo a string
              run: echo "Hello world"
            - name: Multi line command
              run: |
                  node -v
                  npm -v
