name: First Workflow
# This is the even the workflows below will run on
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Echo a string
              run: echo "Hello world"
            - name: Multi line command
              run: |
                  node -v
                  npm -v

    # A job runner
    parallel-job-macos:
        # specifies the OS the workflow should run on
        runs-on: macos-latest
        # The steps to run on the workflow
        steps:
            #Name of a job
            - name: View SW version
              # Command to run
              run: sw_vers
    dependant-job:
        runs-on: windows-latest
        # You can add needs if you require a jobs to only run on certain paramters
        # Or previpus jobs
        needs: run-shell-commands
        steps:
            - name: Windows Jobs "Echo string"
              run: Write-Output "Windows String"

            - name: Command Does not exist
              run: thiscommandDoesnotexist
