name: Working Dirs & Shells
on: [push]
# Specify with shell to use
defaults:
    run:
        shell: bash
jobs:
    display-working-dirs-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display working Directory and List Files - Ubuntu
              run: |
                  pwd
                  ls -a
                  mkdir test-folder
                  echo $GITHUB_SHA
                  echo $GITHUB_REPOSITORY

    # Windows jobs
    # ehco $GITHUB_WORKSPACE
    display-working-dirs-info-windows:
        runs-on: windows-latest
        steps:
            - name: Display working Directory and List Files - Windows
              run: |
                  pwd 
                  ls -a
                  echo $GITHUB_SHA
                  echo $GITHUB_REPOSITORY
            # Change a working dir
            - name: Change working Directory
              working-directory: /d/a/
              run: pwd

    display-working-dirs-info-windows-overide:
        runs-on: windows-latest
        # Overide shell
        defaults:
            run:
                shell: pwsh
        steps:
            - name: Display working Directory and List Files - Windows
              #
              #when using windows shell, to read from env,you add a $env before the variable
              run: |
                  Get-Location
                  dir

                  echo $env:GITHUB_SHA
                  echo $env:GITHUB_REPOSITORY
                  echo $env:GITHUB_WORKSPACE
