name: Workflow Commands
on: [push]

jobs:
    testing-workflow-commnads:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              # Specific format to display an error message ::error::
              run: echo "::error::Missing semicolon"
