name: Working Dirs & Shells
on: [push]

jobs:
    display-working-dirs-info:
        runs-on: ubuntu-latest
        steps:
            - name: Displa working Directory and List Files - Ubuntu
              run: |
                  pwd
                  ls -a
                  echo $GITHUB_SHA
                  echo $GITHUB_REPOSITORY
                  ehco $GITHUB_WORKSPACE

    display-working-dirs-info-windows:
        runs-on: windows-latest
        steps:
            - name: Displa working Directory and List Files - Windows
              run: |
                  pwd
                  ls -a
                  mkdir test-folder
                  echo $GITHUB_SHA
                  echo $GITHUB_REPOSITORY
                  ehco $GITHUB_WORKSPACE
